spring:
  application:
    name: lovable
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable
    username: postgres
    password: waris1918
    driver-class-name: org.postgresql.Driver
# 1. Expose the Prometheus endpoint over the web
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 8080
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl
stripe:
  api:
    secret: sk_test_51SmnIvSFMybZXBrzpJsosWyT8vcQVn9UcB1NGyYPOGJZKZNHmqdFTbpdS7PLTGWhqO4cMXXRwm0Lz62hdqxjF8yG00qjh9IQwX
  webhook:
    secret: whsec_c3b65da3933fbd2e571ff2bed8623228584c3084a4973c94984d4407a56c2c14
client-url: http://localhost:5173


